"""initial_schema

Revision ID: 1024d127654a
Revises: 
Create Date: 2026-04-01 21:19:15.457809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1024d127654a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.String(length=64), nullable=False),
    sa.Column('opportunity_type', sa.String(length=32), nullable=False),
    sa.Column('target_reddit_id', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('conversation_theme', sa.Text(), nullable=True),
    sa.Column('relevant_philosophy', sa.Text(), nullable=True),
    sa.Column('strategic_direction', sa.Text(), nullable=True),
    sa.Column('reported', sa.Boolean(), nullable=False),
    sa.Column('analysed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', name='uq_analyses_opportunity_id')
    )
    op.create_index(op.f('ix_analyses_opportunity_id'), 'analyses', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_analyses_target_reddit_id'), 'analyses', ['target_reddit_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('new_posts', sa.Integer(), nullable=False),
    sa.Column('updated_posts', sa.Integer(), nullable=False),
    sa.Column('opportunities_found', sa.Integer(), nullable=False),
    sa.Column('analyses_completed', sa.Integer(), nullable=False),
    sa.Column('reports_generated', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('reddit_id', sa.String(length=16), nullable=False),
    sa.Column('subreddit', sa.String(length=128), nullable=False),
    sa.Column('subreddit_searched', sa.String(length=128), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('permalink', sa.Text(), nullable=False),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('is_video', sa.Boolean(), nullable=True),
    sa.Column('over_18', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('upvote_ratio', sa.Float(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('age_hours', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('reddit_created_utc', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reddit_id', name='uq_posts_reddit_id')
    )
    op.create_index(op.f('ix_posts_reddit_id'), 'posts', ['reddit_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('reddit_id', sa.String(length=16), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_replies', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('reddit_created_utc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reddit_id', name='uq_comments_reddit_id')
    )
    op.create_index(op.f('ix_comments_reddit_id'), 'comments', ['reddit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_reddit_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_posts_reddit_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('runs')
    op.drop_index(op.f('ix_analyses_target_reddit_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_opportunity_id'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
